"""add shadowing spec 6

Revision ID: 70f6fae95c49
Revises: b8706927c988
Create Date: 2026-04-07 17:06:10.801565
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f6fae95c49'
down_revision = 'b8706927c988'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_shadowing_applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('discipline', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentor_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('mentor_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'assigned'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_shadowing_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_audit_logs_actor_action_created'), table_name='audit_logs')
    op.drop_index(op.f('ix_notifications_recipient_unread'), table_name='notifications')
    op.drop_index(op.f('ix_students_discipline_active'), table_name='students')
    op.drop_index(op.f('ix_survey_submissions_template_status'), table_name='survey_submissions')
    op.drop_index(op.f('ix_sessions_posting_id'), table_name='teaching_sessions')
    op.drop_index(op.f('ix_sessions_status_created'), table_name='teaching_sessions')
    op.drop_index(op.f('ix_tutors_discipline_active'), table_name='tutors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tutors_discipline_active'), 'tutors', ['discipline', 'is_active'], unique=False)
    op.create_index(op.f('ix_sessions_status_created'), 'teaching_sessions', ['approval_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_sessions_posting_id'), 'teaching_sessions', ['posting_id'], unique=False)
    op.create_index(op.f('ix_survey_submissions_template_status'), 'survey_submissions', ['template_id', 'status'], unique=False)
    op.create_index(op.f('ix_students_discipline_active'), 'students', ['discipline', 'is_active'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_unread'), 'notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_action_created'), 'audit_logs', ['created_by', 'action', 'created_at'], unique=False)
    op.drop_table('mentor_assignments')
    op.drop_table('job_shadowing_applications')
    # ### end Alembic commands ###

